# Generated by Django 2.2.2 on 2019-07-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='book_author',
            field=models.TextField(default='me', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogue',
            name='book_barcode',
            field=models.CharField(default='0000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogue',
            name='book_name',
            field=models.TextField(default='good books'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogue',
            name='book_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogue',
            name='book_taker',
            field=models.TextField(default='no one'),
            preserve_default=False,
        ),
    ]
