# Generated by Django 2.2.3 on 2019-07-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20190704_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='issue_date',
            field=models.DateField(default='2019-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='issued_to',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
