# Generated by Django 2.2.3 on 2019-07-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_remove_book_issue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='issued_to',
        ),
    ]
