# Generated by Django 2.2.3 on 2019-07-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_remove_book_issued_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='issue_date',
            field=models.DateField(default='2019-01-01'),
        ),
        migrations.AddField(
            model_name='book',
            name='issued_to',
            field=models.CharField(default='no one', max_length=20),
            preserve_default=False,
        ),
    ]
