# Generated by Django 2.2.3 on 2019-07-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20190706_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='issued_to',
            field=models.CharField(default='', max_length=20),
        ),
    ]
