# Generated by Django 2.2.3 on 2019-07-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20190706_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='issue_date',
            field=models.DateField(default='2019-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='issued_to',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
