# Generated by Django 2.2.3 on 2019-07-07 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('barcode', models.CharField(max_length=20)),
                ('issue_date', models.DateField(default='2019-01-01')),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('email', models.EmailField(db_index=True, max_length=100)),
                ('roll_no', models.CharField(db_index=True, max_length=10)),
                ('circulation_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Book')),
            ],
        ),
    ]
