# Generated by Django 2.2.3 on 2019-07-07 12:29

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Circulation',
        ),
    ]
