# Generated by Django 2.2.3 on 2019-07-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190707_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='circulation_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Circulation'),
        ),
    ]
