# Generated by Django 2.2.3 on 2019-07-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190707_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='roll_no',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
