# Generated by Django 2.2.3 on 2019-07-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190709_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='circulation_history',
        ),
        migrations.AddField(
            model_name='circulation',
            name='username',
            field=models.CharField(default='staff', max_length=20),
            preserve_default=False,
        ),
    ]
